//
//  PatchyRangeTests.swift
//  SwiftlieriOS
//
//  Created by Andrew J Wagner on 6/2/17.
//  Copyright © 2017 Drewag. All rights reserved.
//

import XCTest
import Foundation
import Swiftlier

final class PatchyRangeTests: XCTestCase {
    func testAppendRange() throws {
        var range = PatchyRange<Int>()
        XCTAssertFalse(range.contains(5))

        range.appendRange(from: 3, to: 5)
        XCTAssertFalse(range.contains(2))
        XCTAssertTrue(range.contains(3))
        XCTAssertTrue(range.contains(4))
        XCTAssertTrue(range.contains(5))
        XCTAssertFalse(range.contains(6))

        range.appendRange(from: 8, to: 9)
        XCTAssertFalse(range.contains(2))
        XCTAssertTrue(range.contains(3))
        XCTAssertTrue(range.contains(4))
        XCTAssertTrue(range.contains(5))
        XCTAssertFalse(range.contains(6))
        XCTAssertFalse(range.contains(7))
        XCTAssertTrue(range.contains(8))
        XCTAssertTrue(range.contains(9))
        XCTAssertFalse(range.contains(10))

        range.appendRange(from: 2, to: 3)
        XCTAssertFalse(range.contains(1))
        XCTAssertTrue(range.contains(2))
        XCTAssertTrue(range.contains(3))
        XCTAssertTrue(range.contains(4))
        XCTAssertTrue(range.contains(5))
        XCTAssertFalse(range.contains(6))
        XCTAssertFalse(range.contains(7))
        XCTAssertTrue(range.contains(8))
        XCTAssertTrue(range.contains(9))
        XCTAssertFalse(range.contains(10))

        range.appendRange(from: 9, to: 10)
        XCTAssertFalse(range.contains(1))
        XCTAssertTrue(range.contains(2))
        XCTAssertTrue(range.contains(3))
        XCTAssertTrue(range.contains(4))
        XCTAssertTrue(range.contains(5))
        XCTAssertFalse(range.contains(6))
        XCTAssertFalse(range.contains(7))
        XCTAssertTrue(range.contains(8))
        XCTAssertTrue(range.contains(9))
        XCTAssertTrue(range.contains(10))
        XCTAssertFalse(range.contains(11))

        range.appendRange(from: 0, to: 1)
        XCTAssertFalse(range.contains(-1))
        XCTAssertTrue(range.contains(0))
        XCTAssertTrue(range.contains(1))
        XCTAssertTrue(range.contains(2))
        XCTAssertTrue(range.contains(3))
        XCTAssertTrue(range.contains(4))
        XCTAssertTrue(range.contains(5))
        XCTAssertFalse(range.contains(6))
        XCTAssertFalse(range.contains(7))
        XCTAssertTrue(range.contains(8))
        XCTAssertTrue(range.contains(9))
        XCTAssertTrue(range.contains(10))
        XCTAssertFalse(range.contains(11))

        range.appendRange(from: 11, to: 12)
        XCTAssertFalse(range.contains(-1))
        XCTAssertTrue(range.contains(0))
        XCTAssertTrue(range.contains(1))
        XCTAssertTrue(range.contains(2))
        XCTAssertTrue(range.contains(3))
        XCTAssertTrue(range.contains(4))
        XCTAssertTrue(range.contains(5))
        XCTAssertFalse(range.contains(6))
        XCTAssertFalse(range.contains(7))
        XCTAssertTrue(range.contains(8))
        XCTAssertTrue(range.contains(9))
        XCTAssertTrue(range.contains(10))
        XCTAssertTrue(range.contains(11))
        XCTAssertTrue(range.contains(12))
        XCTAssertFalse(range.contains(13))

        range.appendRange(from: 14, to: 14)
        XCTAssertFalse(range.contains(-1))
        XCTAssertTrue(range.contains(0))
        XCTAssertTrue(range.contains(1))
        XCTAssertTrue(range.contains(2))
        XCTAssertTrue(range.contains(3))
        XCTAssertTrue(range.contains(4))
        XCTAssertTrue(range.contains(5))
        XCTAssertFalse(range.contains(6))
        XCTAssertFalse(range.contains(7))
        XCTAssertTrue(range.contains(8))
        XCTAssertTrue(range.contains(9))
        XCTAssertTrue(range.contains(10))
        XCTAssertTrue(range.contains(11))
        XCTAssertTrue(range.contains(12))
        XCTAssertFalse(range.contains(13))
        XCTAssertTrue(range.contains(14))
        XCTAssertFalse(range.contains(15))

        range.appendRange(from: 13, to: 13)
        XCTAssertFalse(range.contains(-1))
        XCTAssertTrue(range.contains(0))
        XCTAssertTrue(range.contains(1))
        XCTAssertTrue(range.contains(2))
        XCTAssertTrue(range.contains(3))
        XCTAssertTrue(range.contains(4))
        XCTAssertTrue(range.contains(5))
        XCTAssertFalse(range.contains(6))
        XCTAssertFalse(range.contains(7))
        XCTAssertTrue(range.contains(8))
        XCTAssertTrue(range.contains(9))
        XCTAssertTrue(range.contains(10))
        XCTAssertTrue(range.contains(11))
        XCTAssertTrue(range.contains(12))
        XCTAssertTrue(range.contains(13))
        XCTAssertTrue(range.contains(14))
        XCTAssertFalse(range.contains(15))

        range.appendRange(from: 4, to: 10)
        XCTAssertFalse(range.contains(-1))
        XCTAssertTrue(range.contains(0))
        XCTAssertTrue(range.contains(1))
        XCTAssertTrue(range.contains(2))
        XCTAssertTrue(range.contains(3))
        XCTAssertTrue(range.contains(4))
        XCTAssertTrue(range.contains(5))
        XCTAssertTrue(range.contains(6))
        XCTAssertTrue(range.contains(7))
        XCTAssertTrue(range.contains(8))
        XCTAssertTrue(range.contains(9))
        XCTAssertTrue(range.contains(10))
        XCTAssertTrue(range.contains(11))
        XCTAssertTrue(range.contains(12))
        XCTAssertTrue(range.contains(13))
        XCTAssertTrue(range.contains(14))
        XCTAssertFalse(range.contains(15))

        range.appendRange(from: 11, to: 13)
        XCTAssertFalse(range.contains(-1))
        XCTAssertTrue(range.contains(0))
        XCTAssertTrue(range.contains(1))
        XCTAssertTrue(range.contains(2))
        XCTAssertTrue(range.contains(3))
        XCTAssertTrue(range.contains(4))
        XCTAssertTrue(range.contains(5))
        XCTAssertTrue(range.contains(6))
        XCTAssertTrue(range.contains(7))
        XCTAssertTrue(range.contains(8))
        XCTAssertTrue(range.contains(9))
        XCTAssertTrue(range.contains(10))
        XCTAssertTrue(range.contains(11))
        XCTAssertTrue(range.contains(12))
        XCTAssertTrue(range.contains(13))
        XCTAssertTrue(range.contains(14))
        XCTAssertFalse(range.contains(15))

        range.appendRange(from: 10, to: 15)
        XCTAssertFalse(range.contains(-1))
        XCTAssertTrue(range.contains(0))
        XCTAssertTrue(range.contains(1))
        XCTAssertTrue(range.contains(2))
        XCTAssertTrue(range.contains(3))
        XCTAssertTrue(range.contains(4))
        XCTAssertTrue(range.contains(5))
        XCTAssertTrue(range.contains(6))
        XCTAssertTrue(range.contains(7))
        XCTAssertTrue(range.contains(8))
        XCTAssertTrue(range.contains(9))
        XCTAssertTrue(range.contains(10))
        XCTAssertTrue(range.contains(11))
        XCTAssertTrue(range.contains(12))
        XCTAssertTrue(range.contains(13))
        XCTAssertTrue(range.contains(14))
        XCTAssertTrue(range.contains(15))
        XCTAssertFalse(range.contains(16))

        range.appendRange(from: -1, to: 16)
        XCTAssertFalse(range.contains(-2))
        XCTAssertTrue(range.contains(-1))
        XCTAssertTrue(range.contains(0))
        XCTAssertTrue(range.contains(1))
        XCTAssertTrue(range.contains(2))
        XCTAssertTrue(range.contains(3))
        XCTAssertTrue(range.contains(4))
        XCTAssertTrue(range.contains(5))
        XCTAssertTrue(range.contains(6))
        XCTAssertTrue(range.contains(7))
        XCTAssertTrue(range.contains(8))
        XCTAssertTrue(range.contains(9))
        XCTAssertTrue(range.contains(10))
        XCTAssertTrue(range.contains(11))
        XCTAssertTrue(range.contains(12))
        XCTAssertTrue(range.contains(13))
        XCTAssertTrue(range.contains(14))
        XCTAssertTrue(range.contains(15))
        XCTAssertTrue(range.contains(16))
        XCTAssertFalse(range.contains(17))
    }
}
