#if !canImport(ObjectiveC)
import XCTest

extension AgeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AgeTests = [
        ("testYears", testYears),
    ]
}

extension AlwaysEqualTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AlwaysEqualTests = [
        ("testAlwaysEqual", testAlwaysEqual),
    ]
}

extension AngleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AngleTests = [
        ("testAdd", testAdd),
        ("testAddInPlace", testAddInPlace),
        ("testCosine", testCosine),
        ("testDegrees", testDegrees),
        ("testDivideByValue", testDivideByValue),
        ("testDivideByValueInPlace", testDivideByValueInPlace),
        ("testEquals", testEquals),
        ("testGreaterThan", testGreaterThan),
        ("testGreaterThanOrEqual", testGreaterThanOrEqual),
        ("testLessThan", testLessThan),
        ("testLessThanOrEqual", testLessThanOrEqual),
        ("testMultiplyByValue", testMultiplyByValue),
        ("testMultiplyByValueInPlace", testMultiplyByValueInPlace),
        ("testPi", testPi),
        ("testRadians", testRadians),
        ("testSine", testSine),
        ("testSubtract", testSubtract),
        ("testSubtractInPlace", testSubtractInPlace),
        ("testZero", testZero),
    ]
}

extension Array_SortingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Array_SortingTests = [
        ("testInsertAssumingAlreadySorted", testInsertAssumingAlreadySorted),
    ]
}

extension BinarySearchTreeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinarySearchTreeTests = [
        ("testElementsBetween", testElementsBetween),
        ("testInsert", testInsert),
        ("testIterating", testIterating),
    ]
}

extension Bool_FormattingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Bool_FormattingTests = [
        ("testInWords", testInWords),
    ]
}

extension CSVStreamReaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CSVStreamReaderTests = [
        ("testComplexFromData", testComplexFromData),
        ("testComplexFromFile", testComplexFromFile),
        ("testSimpleFromData", testSimpleFromData),
        ("testSimpleFromFile", testSimpleFromFile),
    ]
}

extension CodingKeysTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingKeysTests = [
        ("testDecoder", testDecoder),
        ("testDictionary", testDictionary),
        ("testEncoder", testEncoder),
    ]
}

extension Coding_HelpersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Coding_HelpersTests = [
        ("testCopyUsingCoding", testCopyUsingCoding),
    ]
}

extension Data_Base64Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Data_Base64Tests = [
        ("testByteArrayBase64", testByteArrayBase64),
        ("testByteArrayBase64ForUrl", testByteArrayBase64ForUrl),
        ("testDataBase64", testDataBase64),
        ("testDataBase64ForUrl", testDataBase64ForUrl),
    ]
}

extension Data_ProcessingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Data_ProcessingTests = [
        ("testRangesSeparatedBy", testRangesSeparatedBy),
        ("testsRangesOf", testsRangesOf),
    ]
}

extension Date_HelpersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Date_HelpersTests = [
        ("testBeginningOfDay", testBeginningOfDay),
        ("testBeginningOfMonth", testBeginningOfMonth),
        ("testBeginningOfNextDay", testBeginningOfNextDay),
        ("testBeginningOfNextMonth", testBeginningOfNextMonth),
        ("testBeginningOfNextWeek", testBeginningOfNextWeek),
        ("testBeginningOfWeek", testBeginningOfWeek),
        ("testIsInFuture", testIsInFuture),
        ("testIsInPast", testIsInPast),
        ("testIsThisWeek", testIsThisWeek),
        ("testIsThisYear", testIsThisYear),
        ("testIsToday", testIsToday),
        ("testIsTomorrow", testIsTomorrow),
    ]
}

extension DayTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DayTests = [
        ("testComparison", testComparison),
        ("testDayFromDate", testDayFromDate),
        ("testDescription", testDescription),
        ("testInitFromString", testInitFromString),
    ]
}

extension DelimiterStreamReaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DelimiterStreamReaderTests = [
        ("testNewLinesFromData", testNewLinesFromData),
        ("testNewLinesFromFile", testNewLinesFromFile),
        ("testTabsFromData", testTabsFromData),
        ("testTabsFromFile", testTabsFromFile),
    ]
}

extension Double_FormattingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Double_FormattingTests = [
        ("testAsPercent", testAsPercent),
    ]
}

extension EmailAddressTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EmailAddressTests = [
        ("testEmptyString", testEmptyString),
        ("testEmptyUserString", testEmptyUserString),
        ("testInvalidStrings", testInvalidStrings),
        ("testInvalidUserStrings", testInvalidUserStrings),
        ("testNilString", testNilString),
        ("testNilUserString", testNilUserString),
        ("testValidStrings", testValidStrings),
        ("testValidUserStrings", testValidUserStrings),
    ]
}

extension EventCenterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EventCenterTests = [
        ("testMultipleEvents", testMultipleEvents),
        ("testObserving", testObserving),
        ("testOptionalEvent", testOptionalEvent),
        ("testRemovingObserverForAllEvents", testRemovingObserverForAllEvents),
        ("testRemovingObserverForEvent", testRemovingObserverForEvent),
        ("testWithOperationQueue", testWithOperationQueue),
    ]
}

extension HTMLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HTMLTests = [
        ("testDescription", testDescription),
    ]
}

extension HeartRateFormatterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HeartRateFormatterTests = [
        ("testStringForObject", testStringForObject),
    ]
}

extension JSONTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONTests = [
        ("testData", testData),
        ("testDecode", testDecode),
        ("testEncode", testEncode),
        ("testEquatable", testEquatable),
        ("testInitFromData", testInitFromData),
        ("testInitFromObject", testInitFromObject),
    ]
}

extension LimitedQueueTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LimitedQueueTests = [
        ("testPush", testPush),
        ("testRemoveAll", testRemoveAll),
    ]
}

extension MassTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MassTests = [
        ("testGramsConversions", testGramsConversions),
        ("testKilogramsConversions", testKilogramsConversions),
        ("testOuncesConversions", testOuncesConversions),
        ("testPoundsConversions", testPoundsConversions),
        ("testStonesConversions", testStonesConversions),
        ("testUnitDisplay", testUnitDisplay),
    ]
}

extension MultiCallbackTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MultiCallbackTests = [
        ("testAddingObservers", testAddingObservers),
        ("testRemovingObservers", testRemovingObservers),
        ("testWithMultipleObservers", testWithMultipleObservers),
    ]
}

extension NativeTypesDecoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NativeTypesDecoderTests = [
        ("testDecodableFromRaw", testDecodableFromRaw),
    ]
}

extension NativeTypesEncoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NativeTypesEncoderTests = [
        ("testObjectFromEncodable", testObjectFromEncodable),
    ]
}

extension ObservableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ObservableTests = [
        ("testAutomaticUnsubscribing", testAutomaticUnsubscribing),
        ("testCallOnceOption", testCallOnceOption),
        ("testCallOnceOptionWithInitial", testCallOnceOptionWithInitial),
        ("testSubscribing", testSubscribing),
        ("testTriggerImmediately", testTriggerImmediately),
        ("testUnsubscribing", testUnsubscribing),
    ]
}

extension PatchyRangeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PatchyRangeTests = [
        ("testAppendRange", testAppendRange),
    ]
}

extension PathTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PathTests = [
        ("testAddFile", testAddFile),
        ("testAddLink", testAddLink),
        ("testBaseName", testBaseName),
        ("testCopyFileDirectlyToPath", testCopyFileDirectlyToPath),
        ("testCopyFileToDifferentDirectoryWithDifferentName", testCopyFileToDifferentDirectoryWithDifferentName),
        ("testCopyFileToDifferentDirectoryWithSameName", testCopyFileToDifferentDirectoryWithSameName),
        ("testCopyFileWithinDirectory", testCopyFileWithinDirectory),
        ("testCreateDirectory", testCreateDirectory),
        ("testCreateFile", testCreateFile),
        ("testCreateLink", testCreateLink),
        ("testDelete", testDelete),
        ("testDescription", testDescription),
        ("testDirectory", testDirectory),
        ("testDirectoryContents", testDirectoryContents),
        ("testExsiting", testExsiting),
        ("testExtension", testExtension),
        ("testFile", testFile),
        ("testFileAtSubPath", testFileAtSubPath),
        ("testFileContents", testFileContents),
        ("testFileNamed", testFileNamed),
        ("testHandleForReading", testHandleForReading),
        ("testHandleForReadingAndWriting", testHandleForReadingAndWriting),
        ("testHandleForWriting", testHandleForWriting),
        ("testIsIdenticalTo", testIsIdenticalTo),
        ("testLastModified", testLastModified),
        ("testMoveDirectoryDirectlyToPath", testMoveDirectoryDirectlyToPath),
        ("testMoveDirectoryToDifferentDirectoryWithDifferentName", testMoveDirectoryToDifferentDirectoryWithDifferentName),
        ("testMoveDirectoryToDifferentDirectoryWithSameName", testMoveDirectoryToDifferentDirectoryWithSameName),
        ("testMoveDirectoryWithinDirectory", testMoveDirectoryWithinDirectory),
        ("testMoveFileDirectlyToPath", testMoveFileDirectlyToPath),
        ("testMoveFileToDifferentDirectoryWithDifferentName", testMoveFileToDifferentDirectoryWithDifferentName),
        ("testMoveFileToDifferentDirectoryWithSameName", testMoveFileToDifferentDirectoryWithSameName),
        ("testMoveFileWithinDirectory", testMoveFileWithinDirectory),
        ("testName", testName),
        ("testNonExisting", testNonExisting),
        ("testResolveSymLink", testResolveSymLink),
        ("testSize", testSize),
        ("testString", testString),
        ("testSubdirectory", testSubdirectory),
        ("testSubPathByAppending", testSubPathByAppending),
        ("testWithExtension", testWithExtension),
        ("testWithoutLastComponent", testWithoutLastComponent),
    ]
}

extension Path_CodingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Path_CodingTests = [
        ("testAddEncodable", testAddEncodable),
        ("testAddEncodableArray", testAddEncodableArray),
        ("testAddEncodableDictionary", testAddEncodableDictionary),
        ("testCreateEncodable", testCreateEncodable),
        ("testCreateEncodableArray", testCreateEncodableArray),
        ("testCreateEncodableDictionary", testCreateEncodableDictionary),
    ]
}

extension PercentEncodableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PercentEncodableTests = [
        ("testURLEncodedData", testURLEncodedData),
        ("testURLEncodedDictionary", testURLEncodedDictionary),
        ("testURLEncodedString", testURLEncodedString),
    ]
}

extension PersistenceServiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PersistenceServiceTests = [
        ("testEmpty", testEmpty),
        ("testWithValues", testWithValues),
    ]
}

extension SpecDecoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpecDecoderTests = [
        ("testDecode", testDecode),
    ]
}

extension String_HelpersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__String_HelpersTests = [
        ("testIndexAt", testIndexAt),
        ("testNumberOfCommonSuffixCharacters", testNumberOfCommonSuffixCharacters),
        ("testOffsetCharactersByCount", testOffsetCharactersByCount),
        ("testRepeat", testRepeat),
        ("testTrimmingWhitespaceOnEnds", testTrimmingWhitespaceOnEnds),
    ]
}

extension XMLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLTests = [
        ("testEquatable", testEquatable),
        ("testInitFromData", testInitFromData),
        ("testInitFromObject", testInitFromObject),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AgeTests.__allTests__AgeTests),
        testCase(AlwaysEqualTests.__allTests__AlwaysEqualTests),
        testCase(AngleTests.__allTests__AngleTests),
        testCase(Array_SortingTests.__allTests__Array_SortingTests),
        testCase(BinarySearchTreeTests.__allTests__BinarySearchTreeTests),
        testCase(Bool_FormattingTests.__allTests__Bool_FormattingTests),
        testCase(CSVStreamReaderTests.__allTests__CSVStreamReaderTests),
        testCase(CodingKeysTests.__allTests__CodingKeysTests),
        testCase(Coding_HelpersTests.__allTests__Coding_HelpersTests),
        testCase(Data_Base64Tests.__allTests__Data_Base64Tests),
        testCase(Data_ProcessingTests.__allTests__Data_ProcessingTests),
        testCase(Date_HelpersTests.__allTests__Date_HelpersTests),
        testCase(DayTests.__allTests__DayTests),
        testCase(DelimiterStreamReaderTests.__allTests__DelimiterStreamReaderTests),
        testCase(Double_FormattingTests.__allTests__Double_FormattingTests),
        testCase(EmailAddressTests.__allTests__EmailAddressTests),
        testCase(EventCenterTests.__allTests__EventCenterTests),
        testCase(HTMLTests.__allTests__HTMLTests),
        testCase(HeartRateFormatterTests.__allTests__HeartRateFormatterTests),
        testCase(JSONTests.__allTests__JSONTests),
        testCase(LimitedQueueTests.__allTests__LimitedQueueTests),
        testCase(MassTests.__allTests__MassTests),
        testCase(MultiCallbackTests.__allTests__MultiCallbackTests),
        testCase(NativeTypesDecoderTests.__allTests__NativeTypesDecoderTests),
        testCase(NativeTypesEncoderTests.__allTests__NativeTypesEncoderTests),
        testCase(ObservableTests.__allTests__ObservableTests),
        testCase(PatchyRangeTests.__allTests__PatchyRangeTests),
        testCase(PathTests.__allTests__PathTests),
        testCase(Path_CodingTests.__allTests__Path_CodingTests),
        testCase(PercentEncodableTests.__allTests__PercentEncodableTests),
        testCase(PersistenceServiceTests.__allTests__PersistenceServiceTests),
        testCase(SpecDecoderTests.__allTests__SpecDecoderTests),
        testCase(String_HelpersTests.__allTests__String_HelpersTests),
        testCase(XMLTests.__allTests__XMLTests),
    ]
}
#endif
