#!/bin/bash

if [[ $PLATFORM == "iOS" ]]; then
    xcodebuild test -project SwiftlieriOS.xcodeproj -scheme Swiftlier -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0' | xcpretty -f `xcpretty-travis-formatter`
elif [[ $PLATFORM == "macOS" ]] || [[ $PLATFORM = "Linux" ]]; then
  ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
else
    set -e
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "Testing iOS"
        xcodebuild test -project SwiftlieriOS.xcodeproj -scheme Swiftlier -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0' | xcpretty
        echo "SUCCESS"
        echo
        echo "Testing macOS"
        swift test
        echo "SUCCESS"
    else
        swift test
    fi
fi
